version: "3"
services:
  redis-server:
    image: redis:alpine
    # ports:
    #   - 6378:6379
  app:
    build: .
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - 9000:3000
    # restart: unless-stopped
