name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    # outputs:
    # output1: ${{Job_status.}}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build the Docker image client
        working-directory: ./complex
        run: DOCKER_BUILDKIT=1 docker build -f ./client/Dockerfile ./client

      # - id: Job_status
      # run: echo "::set-output name=test::world" ${{ job.status }}
