name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build the Docker image client
        working-directory: ./complex/client
        run: DOCKER_BUILDKIT=1 docker build --progress=plain -t ${{ secrets.DOCKER_HUB_USERNAME }}/cplx-client .

      - name: Login to Docker Hub
        if: ${{github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Client App
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cplx-client

  auto-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/cplx-nginx

      - name: Login to Docker Hub
        if: ${{github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./complex/nginx
          file: ./Dockerfile
          push: ${{github.event_name != 'pull_request' }}
          tag: ${{ steps.meta.outputs.tags }}
